initialize;
faces = rotateCube(faces, 'x');
faces = rotateCube(faces, 'z');
faces = rotateCube(faces, 'z');
faces = randomize(faces, 20);
faces = doWhiteCross(faces);
faces = doWhiteCorners(faces);
faces = rotateCube(faces, 'x');
faces = rotateCube(faces, 'x');
faces = rotateCube(faces, 'z');
faces = rotateCube(faces, 'z');
faces = doSecondLayer(faces);
faces = topCross(faces);
faces = orientEdges(faces);
clf;
drawCube(faces);
