initialize;
faces = rotateCube(faces, 'x');
faces = rotateCube(faces, 'z');
faces = rotateCube(faces, 'z');
faces = doWhiteCross(faces);
faces = doWhiteCorners(faces);
faces = rotateCube(faces, 'x');
faces = rotateCube(faces, 'x');
faces = rotateCube(faces, 'z');
faces = rotateCube(faces, 'z');
faces = doSecondLayer(faces);
